### ISSUE TITLE
Rozeznanie w technologii przechowywania danych przez Monitor

### ISSUE THREAD

**Issue by piotrokop** [random-development/resources-monitoring-system#14]
Jako bazę przechowującą dane z monitorowania można użyć Prometheusa (https://prometheus.io) - przy zachowaniu pozostałych wymagań. Uwaga: jeśli dane do Prometheusa trzeba będzie “pushować”, potrzebny jest dodatkowy komponent: https://prometheus.io/docs/instrumenting/pushing/ . Alternatywnie sensory muszą wystawiać endpointa, z którego Prometheus czyta dane.

**Comment by boreq** [comment]
Powiadomiono mnie że użycie Prometeusza skończy się bólem i płaczem - polecono mi użycie InfluxDB.

**Comment by boreq** [comment]
Po researchu zmieniłem jednak koncepcję na InfluxDB ponieważ w istocie jest niezwykle proste w obsłudze. Technologia spełniła moje oczekiwania.
