### ISSUE TITLE
Co znaczy "top 10 najbardziej obciążonych maszyn"

### ISSUE THREAD

**Issue by mariebo** [random-development/resources-monitoring-system#47]
@piotrokop wiesz może?

**Comment by piotrokop** [comment]
Wydaje mi sie, ze mozemy wybrac, ze np domyslnie listuje wedlug zuzycia procka. Spytam sie prowadzacego, czy potrzebne bedzie tez listowanie wedlug pozostalych metryk.

**Comment by mariebo** [comment]
Myślę, że możemy zawiesić to pytanie, bo dodałam [parametr METRICS](https://github.com/random-development/cli-client#uruchomnienie-aplikacji-w-kontenerze) do dockera, więc jak trzeba będzie czegoś wiecej to po prostu dorzucimy to z command line'a.
