### ISSUE TITLE
[Gateway] - obsługa metryk złożonych

### ISSUE THREAD

**Issue by 4poznanski** [random-development/resources-monitoring-system#55]
Obsługa metryk złożonych

**Comment by 4poznanski** [comment]
Oczekuję na zaimplementowanie POST i DELETE metryk złożonych w monitorze, ale już teraz endpointy działają

**Comment by boreq** [comment]
Czy oczekujesz działającego endpointa `DELETE`? Na razie nie został on zrealizowany ponieważ jakiś czas temu powiedziano mi, że nie jest potrzebny.

**Comment by 4poznanski** [comment]
@boreq  Tak, oczekuję działającego endpointa DELETE. W wymaganiach jest, że ma być możliwość usuwania pomiarów złożonych. Ponadto tylko użytkownik który stworzył dany pomiar może go usunąć.

**Comment by piotrokop** [comment]
Potwierdzam. Byłoby ekstra, jakby udało się machnąć też delete :>

**Comment by boreq** [comment]
> @boreq Tak, oczekuję działającego endpointa DELETE. W wymaganiach jest, że ma być możliwość usuwania pomiarów złożonych. Ponadto tylko użytkownik który stworzył dany pomiar może go usunąć.

Ok, ale taka walidacja powinna dziać się w gatewayu. Czy monitor ma w ogóle to sprawdzić jeśli nie jest w stanie w ogóle w żaden sposób sprawdzić czy taki user id jest prawdziwy?

**Comment by piotrokop** [comment]
Nie robimy żadnych walidacji. Nie ma w wymaganiach. :)

Edit: Pomyłka. Zgodnie z wymaganiami: "Tylko użytkownik, który utworzył pomiar złożony może go usunąć."

To powinno być sprawdzone na API Gateway. Resztę walidacji olewamy.

**Comment by 4poznanski** [comment]
@boreq nie musisz sprawdzać poprawności userId. Poprawność tokenów jest sprawdzana w Gatewayu. Ja zgodnie z Twoim API przy żądaniu POST(utworzenie metryki złożonej) przesyłam userId. Ja w gatewayu nie przechowuję w ogóle metryk złożonych. Z tego względu, że Ty je przechowujesz, to wystarczy abyś zrobił dodatkową kolumnę 'userId' i przy żądaniu DELETE zrobił ifa sprawdzającego, czy żądanie DELETE ma taki sam userId co metryka złożona. Mogę Ci w body wysyłać userId przy DELETE, np.:
{
     "userId": "213"
}

**Comment by boreq** [comment]
Zaimplementowano `DELETE` w ramach #35.

 Nie ma w tej chwili walidacji user id. Moje zalecenie jest następujące: gateway powinien najpierw pobrać daną metrykę żłożoną i upewnić się, że ten sam użytkownik ją stworzył. Podobnie przy ewentualnej edycji przy pomocy `POST` należy potwierdzić, że ten użytkownik jest właścicielem tej metryki złożonej.

**Comment by 4poznanski** [comment]
Gateway w przypadku próby edycji(czyli dodania metryki złożonej o takiej samej nazwie, resourcu i monitorze jak już istniejąca) oraz próby usunięcia sprawdza czy użytkownik założył tę metrykę. Jeżeli użytkownik ją założył, to ma prawo do edycji i usunięcia. W przypadku gdy użytkownik nie ma uprawnień, zwracany jest status 403 FORBIDDEN.
Sprawdzanie użytkownika odbywa się nie za pomocą userId w jsonie, lecz za pomocą tokenu. Gateway sprawdza w serwerze autoryzacyjnym userId tokenu.
