### ISSUE TITLE
[Monitor][Bug] Dowolny użytkownik może edytować dowolną metrykę złożoną

### ISSUE THREAD

**Issue by 4poznanski** [random-development/resources-monitoring-system#62]
Dowolny użytkownik może edytować oraz usunąć dowolną metrykę złożoną, a tak nie powinno być, gdyż w wymaganiach jest napisane, iż tylko użytkownika który stworzył daną metrykę może ją usunąć(no i edytować pewnie też).

Przykład:
1. Tworzę metrykę złożoną o nazwie "metryka", userId = "jeden"
2. Uaktualniam metrykę złożoną o nazwie "metryka", userId ="dwa" (takie samo żądanie jak w 1 tylko zmieniony userId)
3. W metryce złożonej widnieje userId = "dwa", a nie powinien, bo on nie może aktualizować metryk innych użytkowników 

Przykład:
4. Tworzę metrykę złożoną o nazwie "metryka", userId = "jeden"
5. Usuwam (DELETE) metrykę złożoną o nazwie "metryka", userId ="dwa"(przekazuję userId w JSON). Bez podawania userId również można usunąć.
6. Metryka złożona zostaje usunięta, a nei powinna.

**Comment by boreq** [comment]
Jest to w pełni zamierzone. To, że monitor ma to pole walidować to kolejna dziwna decyzja architektoniczna, która podobnie do rejestrowania monitorów w API gateway miesza odpowiedzialność monitora z odpowiedzialnością API gatewaya. 

To API gateway powinien w pierwszej kolejności pobrać przy pomocy metody `GET` metrykę i upewnić się, że należy do dobrego użytkownika. 

Jeśli jednak chcecie żeby tak było to nie ma problemu i wprowadzę na to fix.

**Comment by 4poznanski** [comment]
Ok, 
tak będzie chyba nawet lepiej, będę pobierał w takim razie GETEM metrykę i sprawdzał użytkownika w Gatewayu. Przepinam na siebie

**Comment by 4poznanski** [comment]
Dodano funkcjonalność.
Gateway w przypadku próby edycji(czyli dodania metryki złożonej o takiej samej nazwie, resourcu i monitorze jak już istniejąca) oraz próby usunięcia sprawdza czy użytkownik założył tę metrykę. Jeżeli użytkownik ją założył, to ma prawo do edycji i usunięcia. W przypadku gdy użytkownik nie ma uprawnień, zwracany jest status 403 FORBIDDEN. 
Sprawdzanie użytkownika odbywa się nie za pomocą userId w jsonie, lecz za pomocą tokenu. Gateway sprawdza w serwerze autoryzacyjnym userId tokenu.
