### ISSUE TITLE
Dodać wylogowywanie użytkownika

### ISSUE THREAD

**Issue by piotrokop** [random-development/resources-monitoring-system#73]
wylogowanie jest dostepne na localhost:7000/logout

**Comment by 4poznanski** [comment]
Poprawne wylogowanie przekierowuje do linku z application.properties serwera autoryzującego: 
spring.security.oauth2.client.registration.first-client.index-uri

Obecnie przekierowanie to jest ustawione na http://localhost:4200 , czyli po poprawnym wylogowaniu przekierowuję do klienta webowego(a on poprawnie przekierowuje na poprawną stronę logowania)
